/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Simple PostgreSQL Client
 #	author : miyako
 #	2016/09/26
 #
 # --------------------------------------------------------------------------------*/

#include "libpq-fe.h"

#if VERSIONMAC
#include <iconv.h>
#define UTF32NATIVE "UTF-32LE"
#endif

#define NDEBUG

#include "libjson/libjson.h"

// --- Simple PostgreSQL Client
void PQ_EXECUTE(sLONG_PTR *pResult, PackagePtr pParams);
